parameters:
#    file_file.example.class: File\FileBundle\Example

services:
#    file_file.example:
#        class: %file_file.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
